version: '3'

services:

  bookstore-project-db:
    image: postgres:latest
    container_name: bookstore-project-db
    networks:
      - bookstore
    environment:
      - POSTGRES_DB=bookstore-project-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  bookstore-payment-db:
    image: postgres:latest
    container_name: bookstore-payment-db
    networks:
      - bookstore
    environment:
      - POSTGRES_DB=bookstore-payment-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432

  bookstore-order-db:
    image: postgres:latest
    container_name: bookstore-order-db
    networks:
      - bookstore
    environment:
      - POSTGRES_DB=bookstore-order-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5434:5432

  bookstore-book-db:
    image: postgres:latest
    container_name: bookstore-book-db
    networks:
      - bookstore
    environment:
      - POSTGRES_DB=bookstore-book-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5435:5432

  bookstore-address-db:
    image: postgres:latest
    container_name: bookstore-address-db
    networks:
      - bookstore
    environment:
      - POSTGRES_DB=bookstore-address-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5436:5432

  kafka:
    container_name: kafka
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - bookstore
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    volumes:
      - ./data/kafka/data:/var/lib/kafka/data

  redpanda-console:
    container_name: redpanda
    image: docker.redpanda.com/vectorized/console:latest
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    ports:
      - "8081:8080"
    networks:
      - bookstore
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:29092"]
    depends_on:
      - "kafka"

  order-service:
    build: './order-service'
    container_name: order-service
    depends_on:
      - bookstore-order-db
      - kafka
    networks:
      - bookstore
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=bookstore-order-db
      - DB_NAME=bookstore-order-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - 8092:8092

  orchestrator-service:
    build: './orchestrator-service'
    container_name: orchestrator-service
    depends_on:
      - kafka
    networks:
      - bookstore
    environment:
      - KAFKA_BROKER=kafka:29092
    ports:
      - 8088:8088

  book-service:
    build: './book-service'
    container_name: book-service
    depends_on:
      - bookstore-book-db
      - kafka
    networks:
      - bookstore
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=bookstore-book-db
      - DB_NAME=bookstore-book-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - 8093:8093

  payment-service:
    build: './payment-service'
    container_name: payment-service
    depends_on:
      - bookstore-payment-db
      - kafka
    networks:
      - bookstore
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=bookstore-payment-db
      - DB_NAME=bookstore-payment-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - 8091:8091

  auth-service:
    build: './auth-service'
    container_name: auth-service
    depends_on:
      - bookstore-project-db
      - kafka
    networks:
      - bookstore
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=bookstore-project-db
      - DB_NAME=bookstore-project-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - 8090:8090

  address-service:
    build: './address-service'
    container_name: address-service
    depends_on:
      - bookstore-address-db
      - kafka
    networks:
      - bookstore
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=bookstore-address-db
      - DB_NAME=bookstore-address-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - 8094:8094

networks:
  bookstore:
    driver: bridge